# APP ENGINE DEPLOYMENT SAMPLE (STANDARD ENVIRONMENT)
# This is a sample that you can use as a template to deploy Strautomator to
# Google App Engine (standard environment). Please note that you must update
# the environment variables to your own secrets and credentials.

runtime: nodejs12
instance_class: F2
automatic_scaling:
    max_instances: 1

handlers:
    - url: /_nuxt
      static_dir: .nuxt/dist/client
      secure: always
    - url: /(.*\.(gif|png|jpg|ico|txt))$
      static_files: static/\1
      upload: static/.*\.(gif|png|jpg|ico|txt)$
      secure: always
    - url: /.*
      script: auto
      secure: always

env_variables:
    NODE_ENV: "production"
    HOST: "0.0.0.0"
    SMU_api_adminToken: "xxx"
    SMU_cookie_secret: "xxx"
    SMU_database_crypto_key: "xxx"
    SMU_database_crypto_iv: "xxx"
    SMU_gcp_projectId: "xxx"
    SMU_mailer_from: "xxx"
    SMU_mailer_smtp_auth_user: "xxx"
    SMU_mailer_smtp_auth_pass: "xxx"
    SMU_maps_api_key: "xxx"
    SMU_strava_api_clientId: "xxx"
    SMU_strava_api_clientSecret: "xxx"
    SMU_strava_api_verifyToken: "xxx"
    SMU_weather_darksky_secret: "xxx"
    SMU_weather_openweathermap_secret: "xxx"
    SMU_weather_weatherbit_secret: "xxx"
